language: php
script: find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
notifications:
  slack:
    secure: ZslruaPwvC9Eqr1AFPl/p82UyH0oMy9HBWKROF+z7E/N/nlItGjojAkTBbRRAJIzi58YOeJDVbmTjHvI2MYYeYWX1zawkcjVfJa4RDmeqTmj937hBQW/bKEVN3WqNnL0OewDFVXENETzWs3I63e7par7SO7/SR5gJrMKLtK9fTyGi74hgqVWyQSCLNBgZBMPkNmoZ9sfSCgijPxkXYMNJKTgxWYXvAMevWyfQXv+SoBCQ1hh1hsM4LgT5he5id54iEZY7yVEQZkzsZ0HRDnD+JcquJTuaN2B+PNaHL4RtxhWdNjvnkrHJoB0/F3OKuGs0++6T/25jCow0svfrOk9/dDKlH0R1+deCfH0AMj2QM022Ww10iZHDZffwBkUpFayXArCbmUsEdo0IT8Ra1EUx+7E+0+3f4ihlJez6/wwkWfkKfVwNfkhmu4SnwRzf9r0Ryex/xBngDcKerkQ6xsWr3lc6+wQDWZV60224716nMoFZdZIDAvKc+/fNAIc/PtSvZixawEERLV9XyglBMUwKFqyaQtyw1KENxGKbobP9HBkd5cVzGD29Eu7z3xQyN256/NacGu7vyUawyfh0czjkcvHkrrXbmOljmQOwDf1KB/cWFdASO3VFSKfTPE4zgBzjzgN9iEnKslwfHw/z8FRYuCBdXasST+ufln4/j5u3wE=
  email: false
before_deploy:
- git archive --format=zip --output=yap-${TRAVIS_BUILD_NUMBER}.zip HEAD
deploy:
  provider: releases
  api_key:
    secure: p9bkpfNzuZey0m3kNv42+mNdJGy1ajcC6/HVXkA+3hHqrBslBgtoPUBlpzfPy5jS+QIdc4lgtMmS0jRe129NpLUeXAEcmUHBvBtyeHktjmKFz9cju57CyJBMg4MecNU3EWBrNNvIqQkgcoJXjsLccVZcpJJQZkRd7cq+A/bFf/eahv8VyoEo5rA/U69ryZfzDsPASFCN+RkSa4Oe0NnyHCk9bzvlAzrUdRTFO7zZqJ7cM7GUDs7DCDuL1UYO4yutfynIfteaLCElEJ6yoqrLUywsbRSTXaIpbMa3vA7Wfrjs0zcbKAAvkrpQXyHzIr+GPbtSWI2etU+L51ADH9oLfEnn5Lly0dc8LFlb1284EOU1U6Ug94PXvOfybaMPOwlt0c7qQfzg8A3mw2B9qT6AXxR68n5qOZziMw0YzoxUSt8PlVjW7yCQQ48wPebC8rv/Xo67Hax5bnPmHqrGFTn0TzsLQAp4QpY5knM4VKvtXrmDciM3zt09m0lBZ5bJtqMl25/YkNt2H+KWT6XGfmhBaln43lCzaiqN0xl5F2gs0npRhUY/hShlM5J1tMPx/TCeezBEDIiU7L5LAzxkyhSm4FWd4NOiQQs8rZbZEmS+Antu903lZKgPAopQoRibxj25bvQhmZeO/pntIzf8LgY8YyW75Fbsh6XC6rXxQj1lEqc=
  file: yap-${TRAVIS_BUILD_NUMBER}.zip
  skip_cleanup: true
  draft: true
